"""Load synthetic trajectory JSONL into BigQuery.

Creates dataset and table if missing. The table is partitioned by batch_id
(via clustering — partition by string is not supported, so we cluster on it).

Usage:
    python data-gen/load_to_bq.py --batch initial
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from google.cloud import bigquery
from google.cloud.bigquery import LoadJobConfig, SchemaField, SourceFormat
from google.cloud.exceptions import NotFound

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT_DIR = REPO_ROOT / "data" / "synthetic"

DEFAULT_PROJECT = os.environ.get("GCP_PROJECT", "ai-agent-hackathon-499013")
DEFAULT_LOCATION = os.environ.get("BQ_LOCATION", "asia-northeast1")
DEFAULT_DATASET = os.environ.get("BQ_DATASET", "devpath")
TABLE_NAME = "trajectories"

SCHEMA = [
    SchemaField("employee_id", "STRING", mode="REQUIRED"),
    SchemaField("step", "INT64", mode="REQUIRED"),
    # `roles` is an array of {role, years} structs — multi-role steps and
    # per-role tenure information together. Replaces v1 fields `role` and
    # `tenure_months`.
    SchemaField(
        "roles",
        "RECORD",
        mode="REPEATED",
        fields=[
            SchemaField("role", "STRING", mode="REQUIRED"),
            SchemaField("years", "FLOAT64", mode="REQUIRED"),
        ],
    ),
    SchemaField("tech_stack", "STRING", mode="REPEATED"),
    SchemaField("seniority", "STRING", mode="NULLABLE"),
    SchemaField("archetype", "STRING", mode="NULLABLE"),
    SchemaField("batch_id", "STRING", mode="REQUIRED"),
]


def ensure_dataset(client: bigquery.Client, dataset_id: str, location: str) -> None:
    full_id = f"{client.project}.{dataset_id}"
    try:
        client.get_dataset(full_id)
        print(f"Dataset {full_id} already exists")
    except NotFound:
        ds = bigquery.Dataset(full_id)
        ds.location = location
        ds.description = "DevPath Navigator — synthetic career trajectories and embeddings"
        client.create_dataset(ds)
        print(f"Created dataset {full_id} in {location}")


def ensure_table(client: bigquery.Client, dataset_id: str, recreate: bool = False) -> bigquery.Table:
    table_ref = bigquery.TableReference.from_string(
        f"{client.project}.{dataset_id}.{TABLE_NAME}"
    )
    if recreate:
        try:
            client.delete_table(table_ref)
            print(f"Dropped existing table {table_ref}")
        except NotFound:
            pass
    try:
        existing = client.get_table(table_ref)
        existing_fields = {f.name for f in existing.schema}
        expected_fields = {f.name for f in SCHEMA}
        if existing_fields != expected_fields:
            raise SystemExit(
                f"Table {table_ref} has schema {sorted(existing_fields)} but the loader "
                f"expects {sorted(expected_fields)}. Re-run with --recreate-table to drop and rebuild it."
            )
        return existing
    except NotFound:
        table = bigquery.Table(table_ref, schema=SCHEMA)
        table.clustering_fields = ["batch_id", "archetype"]
        table.description = "Synthetic engineer career trajectories. Generated by data-gen/generate.py."
        client.create_table(table)
        print(f"Created table {table_ref}")
        return client.get_table(table_ref)


def delete_batch(client: bigquery.Client, dataset_id: str, batch: str) -> None:
    """Idempotency: remove previous rows for this batch before reloading."""
    sql = f"""
    DELETE FROM `{client.project}.{dataset_id}.{TABLE_NAME}`
    WHERE batch_id = @batch
    """
    job = client.query(
        sql,
        job_config=bigquery.QueryJobConfig(
            query_parameters=[bigquery.ScalarQueryParameter("batch", "STRING", batch)]
        ),
    )
    job.result()
    if job.num_dml_affected_rows:
        print(f"Deleted {job.num_dml_affected_rows} pre-existing rows for batch '{batch}'")


def load_jsonl(client: bigquery.Client, dataset_id: str, jsonl: Path) -> None:
    table_ref = bigquery.TableReference.from_string(
        f"{client.project}.{dataset_id}.{TABLE_NAME}"
    )
    job_config = LoadJobConfig(
        schema=SCHEMA,
        source_format=SourceFormat.NEWLINE_DELIMITED_JSON,
        write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
    )
    with jsonl.open("rb") as f:
        job = client.load_table_from_file(f, table_ref, job_config=job_config)
    job.result()
    print(f"Loaded {job.output_rows} rows from {jsonl}")


def summarize(client: bigquery.Client, dataset_id: str) -> None:
    sql = f"""
    SELECT
      batch_id,
      archetype,
      COUNT(DISTINCT employee_id) AS employees,
      COUNT(*) AS row_count
    FROM `{client.project}.{dataset_id}.{TABLE_NAME}`
    GROUP BY batch_id, archetype
    ORDER BY batch_id, archetype
    """
    rows = list(client.query(sql).result())
    print("\nCurrent contents of trajectories:")
    print(f"  {'batch_id':<10s} {'archetype':<22s} {'employees':>10s} {'rows':>8s}")
    for r in rows:
        print(f"  {r.batch_id:<10s} {r.archetype:<22s} {r.employees:>10d} {r.row_count:>8d}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--batch", required=True, help="Batch to load (e.g. initial, drift)")
    ap.add_argument("--project", default=DEFAULT_PROJECT)
    ap.add_argument("--dataset", default=DEFAULT_DATASET)
    ap.add_argument("--location", default=DEFAULT_LOCATION)
    ap.add_argument("--input", type=Path, default=None,
                    help="Input JSONL path (default: data/synthetic/<batch>.jsonl)")
    ap.add_argument("--recreate-table", action="store_true",
                    help="Drop and recreate the trajectories table (use after a schema change).")
    args = ap.parse_args()

    input_path = args.input or (DEFAULT_INPUT_DIR / f"{args.batch}.jsonl")
    if not input_path.exists():
        print(f"ERROR: input file not found: {input_path}", file=sys.stderr)
        print("Hint: run `python data-gen/generate.py --batch " + args.batch + "` first.", file=sys.stderr)
        return 1

    client = bigquery.Client(project=args.project, location=args.location)
    ensure_dataset(client, args.dataset, args.location)
    ensure_table(client, args.dataset, recreate=args.recreate_table)
    delete_batch(client, args.dataset, args.batch)
    load_jsonl(client, args.dataset, input_path)
    summarize(client, args.dataset)
    return 0


if __name__ == "__main__":
    sys.exit(main())
